namespace WheelHouse.Core.Models;

/// <summary>
/// An atomic unit of work generated by Gemini and handed to Claude.
/// Supports Test-Driven Handoff: <see cref="VerificationCommand"/> must run and pass
/// before the task can be marked <see cref="WorkItemStatus.Completed"/>.
/// </summary>
public class TaskItem
{
    public int Id { get; set; }

    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;

    public WorkItemStatus Status { get; set; } = WorkItemStatus.Pending;

    /// <summary>Ordering within the session plan.</summary>
    public int Sequence { get; set; }

    /// <summary>
    /// Optional command (e.g. <c>dotnet test --filter X</c>) Claude must run and pass
    /// before this task is considered complete.
    /// </summary>
    public string? VerificationCommand { get; set; }

    /// <summary>Captured output of the last verification run.</summary>
    public string? VerificationOutput { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? CompletedAt { get; set; }

    public int AgentSessionId { get; set; }
    public AgentSession? AgentSession { get; set; }
}
